---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: naveengarg-dev-tls
spec:
  secretName: naveengarg-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - naveengarg.dev
    - www.naveengarg.dev
  acme:
    config:
        - http01:
            ingressClass: nginx
          domains:
            - naveengarg.dev
            - www.naveengarg.dev
---