---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: portfoliowebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      name: portfolio-pod
      app: portfoliowebsite
  template:
    metadata:
      labels:
        name: portfolio-pod
        app: portfoliowebsite
    spec:
      containers:
      - name: portfolio
        image: gcr.io/project-portfolio-278518/portfolio-app@sha256:89b9f12fabf980e7151c3d47bf7a377de4b081a564207346206413cf603e0707
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  labels:
    name: portfolio-service
    app: portfoliowebsite
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: portfolio-pod
    app: portfoliowebsite
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    # cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  # tls:
  #   - hosts:
  #       - naveengarg.dev
  #       - www.naveengarg.dev
  #     secretName: naveengarg-dev
  rules:
    - host: 35.201.223.236
      http:
        paths:
        - path: /
          backend:
            serviceName: portfolio-service
            servicePort: 80
    # - host: www.naveengarg.dev
    #   http:
    #     paths:
    #     - path: /
    #       backend:
    #         serviceName: portfolio-service
    #         servicePort: 80 
---
