---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: naveengarg-dev-tls
spec:
  secretName: naveengarg-dev
  dnsNames:
    - naveengarg.dev
    - www.naveengarg.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - naveengarg.dev
      - www.naveengarg.dev
---